name: Build and Deploy
on:
  push:
    branches:
      - master
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: target/release  # The folder the action should deploy.
          clean: true  # Automatically remove old files from the deployment branch
          commit-message: Deploy latest build